name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - azure-static-web-apps

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/"
          skip_app_build: true
